### ISSUE TITLE
allowfullscreen on iframe to work on firefox

### ISSUE THREAD

**Issue by leonardopaiva** [dirkk0/multiplay#1]
hello, i needed to add "allowfullscreen" on iframes to work on firefox.

"iframe src="multiplay.html?me=u1" height="300" width="300" allowfullscreen></iframe"

thanks for your work.

**Comment by dirkk0** [comment]
Ah, cool - thank you! Will put it in the code.

**Comment by dirkk0** [comment]
Actually I found a better solution: Firefox doesn't need to switch to Fullscreen anymore, if you need Pointerlock. So I commented out the whole fullscreen part, which removes a whole lot of workaround code.

Again: thanks for bringing this to my attention!
